name: nearby_connections
description: Plugin for the android NearbyConnections API. Bytes and Files Supported.
version: 1.0.3
homepage: https://github.com/mannprerak2/nearby_connections

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.pkmnapps.nearby_connections
    pluginClass: NearbyConnectionsPlugin
